# See documentation at http://goreleaser.com
builds:
  - binary: akash
    main: ./cmd/akash
    goarch: [amd64]
    goos: [linux,darwin,windows]
    ldflags: -s -w -X github.com/ovrclk/akash/version.version={{.Version}} -X github.com/ovrclk/akash/version.commit={{.Commit}} -X github.com/ovrclk/akash/version.date={{.Date}}

  - binary: akashd
    main: ./cmd/akashd
    goarch: [amd64]
    goos: [linux,darwin]
    ldflags: -s -w -X github.com/ovrclk/akash/version.version={{.Version}} -X github.com/ovrclk/akash/version.commit={{.Commit}} -X github.com/ovrclk/akash/version.date={{.Date}}

archive:
  files:
    - none*

checksum:
  # You can change the name of the checksums file.
  # Default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`.
  name_template: "{{ .ProjectName }}_checksums.txt"

  # Algorithm to be used.
  # Accepted options are sha256, sha512, sha1, crc32, md5, sha224 and sha384.
  # Default is sha256.
  algorithm: sha256

dockers:
  - binaries: 
    - akash
    dockerfile: _build/Dockerfile.akash
    goos: linux
    goarch: amd64
    image_templates:  
    - "ovrclk/akash:latest"
    - "ovrclk/akash:{{ .Tag }}"
    - "ovrclk/akash:v{{ .Major }}"
    - "ovrclk/akash:v{{ .Major }}{{ .Minor }}"

  - binaries: 
    - akashd
    dockerfile: _build/Dockerfile.akashd
    goos: linux
    goarch: amd64
    image_templates:  
    - "ovrclk/akashd:latest"
    - "ovrclk/akashd:{{ .Tag }}"
    - "ovrclk/akashd:{{ .Tag }}"
    - "ovrclk/akashd:v{{ .Major }}"
    - "ovrclk/akashd:v{{ .Major }}{{ .Minor }}"

brew:
  name: akash

  github:
    owner: ovrclk
    name: homebrew-tap

  homepage: "https://akash.network"
  description: "Blockchain-powered decentralized compute platform"

  install: |
    bin.install "akash"
    bin.install "akashd"

release:
  github:
    owner: ovrclk
    name: akash
  prerelease: auto
  draft: false
