language: go

sudo: false

git:
  depth: 50

env:
  global:
    - TEST_DELAY_THREAD_START=10ms

stages:
  - test
  - image
  - test-skipped
  - release

jobs:
  include:

    - name: test
      os: linux
      go: 1.9
      script:
        - make build
        - make test-vet
        - make coverdeps-install
        - make test-cover

    - name: test
      os: linux
      go: "1.10"
      script:
        - make build
        - make test-vet
        - make test
        - make integrationdeps-install
        - make test-integration

    - name: test
      os: linux
      go: master
      script:
        - make build
        - make test-vet
        - make test
      if: type = cron

    - name: test
      os: osx
      osx_image: xcode9.3beta
      go: "1.9.2"
      script:
        - make build
        - make test-vet
        - make test
      if: type = cron

    - name: image
      os: linux
      go: "1.10"
      services: [docker]
      script:
        - make image
      if: type = cron

    - name: test-skipped
      os: linux
      go: "1.10"
      sudo: required
      env: TEST_UNSKIP=true
      script:
        - go test -v -count=1 $(glide novendor)
      if: type = cron

    - name: release
      os: linux
      go: "1.10"
      services: [docker]
      script:
        - docker build --rm -t ovrclk/akash .
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker tag ovrclk/akash "ovrclk/akash:$TRAVIS_TAG"
        - docker push "ovrclk/akash:$TRAVIS_TAG"
        - docker tag ovrclk/akash ovrclk/akash:latest
        - docker push ovrclk/akash:latest
        - go get github.com/goreleaser/goreleaser
        - $GOPATH/bin/goreleaser
      if: tag =~ ^v AND fork = false

matrix:
  allow_failures:
    - env: TEST_UNSKIP=true

cache:
  directories:
    - $HOME/.glide

install:
  - mkdir -p "$GOPATH/bin"
  - curl https://glide.sh/get | sh
  - make deps-install
