---
services:
  web:
    image: nginx
    expose:
      - port: 80
        to:
          - global: true

profiles:

  compute:
    web:
      cpu: 2
      memory: 3
      disk: 5

  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        web: 8

deployment:
  web:
    westcoast:
      profile: web
      count: 20
