name: integration-tests

on:
  pull_request:
    branches:
      - master
      - mainnet/main
  push:
    branches:
      - master
      - mainnet/main

env:
  BUILD_MAINNET: ${{ github.ref == 'refs/heads/mainnet/main' || github.base_ref == 'refs/heads/mainnet/main' }}

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: make test-integration
