name: upgrades
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      tag:

jobs:
  test:
    runs-on: upgrade-tester
    needs:
      - ensure-release
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - name: set environment
        uses: HatsuneMiku3939/direnv-action@v1
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: configure variables
        run: |
          echo "RELEASE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          test_required=$(./script/upgrades.sh test-required ${{ github.event.inputs.tag }})
          echo "TEST_REQUIRED=$test_required" >> $GITHUB_ENV
      - name: run test
        if: env.TEST_REQUIRED == 'true'
        run: |
          cd tests/upgrade
          UPGRADE_BINARY_VERSION=${{ env.RELEASE_TAG }} make test
      - name: dump stderr
        if: always() && steps.test.outcome != 'skipped'
        run: cat .cache/run/upgrade/stderr.log
      - name: upload stderr
        if: always() && steps.test.outcome != 'skipped'
        uses: actions/upload-artifact@v3
        with:
          name: stderr.log
          path: .cache/run/upgrade/stderr.log
      - name: upload stdout
        if: always() && steps.test.outcome != 'skipped'
        uses: actions/upload-artifact@v3
        with:
          name: stdout.log
          path: .cache/run/upgrade/stdout.log
